"use client";
import { useState, useEffect } from "react";
import { darkTheme, lightTheme } from "./theme/themes";
import { ThemeProvider, CssBaseline } from "@mui/material";
import ThemeSwitchButton from "../components/ThemeSwitchButton";
export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const [activeTheme, setActiveTheme] = useState(lightTheme);
    const [selectedTheme, setSelectedTheme] = useState<"light" | "dark">(
        "light"
    );
    const getActiveTheme = (themeMode: "light" | "dark") => {
        return themeMode === "light" ? lightTheme : darkTheme;
    };
    const toggleTheme = () => {
        const desiredTheme = selectedTheme === "light" ? "dark" : "light";

        setSelectedTheme(desiredTheme);
    };
    useEffect(() => {
        setActiveTheme(getActiveTheme(selectedTheme));
    }, [selectedTheme]);

    return (
        <html lang='en'>
            <head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </head>

            <body>
                <ThemeProvider theme={activeTheme}>
                    <CssBaseline />
                    {children}
                    <ThemeSwitchButton
                        activeTheme={activeTheme}
                        toggleTheme={toggleTheme}
                    />
                </ThemeProvider>
            </body>
        </html>
    );
}
